### ISSUE TITLE
How this repository should be organize ? 

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/evocrash-usecases-output#1]
Right now I have the feeling that the repository directories are not well organized.

At least we could have the following path to identify a test case: `/{project}/{softwareVersion}/{testName}/`

However I don't know if the best is to have:

```
sucessfulTest/{project}/{softwareVersion}/{testName}/
testNotGenerated/{project}/{softwareVersion}/{testName}/
exception/{project}/{softwareVersion}/{testName}/
timeoutTest/{project}/{softwareVersion}/{testName}/
```

or
```
/{project}/{softwareVersion}/{testName}/sucessfulTest
/{project}/{softwareVersion}/{testName}/testNotGenerated
/{project}/{softwareVersion}/{testName}/exception
/{project}/{softwareVersion}/{testName}/timeoutTest
```

Maybe the first directory could also match the EvoCrash version. 

What do you think about my suggestion to organize directories ? Do you think about other upgrade ?

**Comment by pderakhshanfar** [comment]
I think it is good if we only put the successful tests (tests that can replicate stack trace) in this repository.
Since this repository is for getting feedback from the developers on different projects about the generated tests, I suggest organizing the paths only according to the project name and their version. So, I agree with `/{project}/{softwareVersion}/{testName}/`

**Comment by xdevroey** [comment]
This repository should report both successful and unsuccessful tries with EvoCrash by the partners. This will help us to identify issues and prioritize future developments of EvoCrash. I suggest to have the following structure for the folders: `/{project}/{softwareVersion}/{issue or crash identifier}/`.
